parameters:
#    nie_simple_form.example.class: Nie\SimpleFormBundle\Example

services:
#    nie_simple_form.example:
#        class: %nie_simple_form.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
